BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_miles
            text: ''

        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
                on_press: app.handle_increment(+1) #, app.handle_update()
            BoxLayout:
                orientation: 'vertical'
                Button:
                    text: 'Down'
                    on_press: app.handle_increment(-1)

    Button:
        text: 'Convert miles to km'
        on_press: app.handle_conversion(input_miles.text)
    Label:
        id: output_label
        text: ''