BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            font_size: '50'
            id: input_miles
            text: ''
            on_text: app.handle_conversion()

        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.25
            Button
                text: 'Up'
                on_press: app.handle_increment(+1) #, app.handle_update()
            BoxLayout:
                orientation: 'vertical'
                Button:
                    text: 'Down'
                    on_press: app.handle_increment(-1)

#    Button:
#        text: 'Convert miles to km'
##        on_press: app.handle_conversion()
    Label:
        id: output_label
        text: ''
        font_size: '50'
        color: (1, 1, 0, 1)