BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_miles
            text: ''

        BoxLayout:
            orientation: 'vertical'
            Button:

            BoxLayout:
                orientation: 'vertical'
                Button:

    Button:
        text: 'Convert miles to km'
    Label:
        id: output_label
        text: ''